language: php

php:
    - 7.2
    - hhvm
    - nightly



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



matrix:
    allow_failures:
        - php: nightly
        - php: hhvm



before_script:
    - make install



script:
    - make check test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/1da19be791078d3b7fff

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
